drop table if exists `tbstats_goalsprojection`;
create table `tbstats_goalsprojection` (
  `fixtureid` bigint not null,
/*  `ct` varchar(50) default null,
  `lg` varchar(50) default null,
  `ss` varchar(50) default null,
  `dt` datetime default null,
  `hm` varchar(50) default null,
  `vs` varchar(50) default null,
  `sh` int default null,
  `sv` int default null,
  `rsl` varchar(1) default null,
  `odd_1` float default null,
  `odd_x` float default null,
  `odd_2` float default null, */
  `avg_g_h` float default null,
  `last_goal_h` int default null,
  `1st_g_h` float default null,
  `2nd_g_h` float default null,
  `3rd_g_h` float default null,
  `avg_g_v` float default null,
  `last_goal_v` int default null,
  `1st_g_v` float default null,
  `2nd_g_v` float default null,
  `3rd_g_v` float default null,
  `avg_a_h` float default null,
  `last_against_h` int default null,
  `1st_a_h` float default null,
  `2nd_a_h` float default null,
  `3rd_a_h` float default null,
  `avg_a_v` float default null,
  `last_against_v` int default null,
  `1st_a_v` float default null,
  `2nd_a_v` float default null,
  `3rd_a_v` float default null,
  primary key (`fixtureid`)
) engine=InnoDB default charset=latin1;
