USE [SoccerSoft]
GO

DECLARE @Date DATETIME 

SELECT
	@Date = GETDATE()

TRUNCATE TABLE [dbo].[tbCore_Market]
INSERT INTO [dbo].[tbCore_Market] ([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ESPN', 'ESPN Website', 1, 1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Market] ([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SoccerWay', 'SoccerWay Website', 1, 1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Market] ([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('OddsPortal', 'OddsPortal Website', 1, 1,@Date,1,@Date)


TRUNCATE TABLE [dbo].[tbCore_Country]
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('---','Default',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ALA','AALAND ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AFG','AFGHANISTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ALB','ALBANIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DZA','ALGERIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ASM','AMERICAN SAMOA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AND','ANDORRA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AGO','ANGOLA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AIA','ANGUILLA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ATA','ANTARCTICA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ATG','ANTIGUA AND BARBUDA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ARG','ARGENTINA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ARM','ARMENIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ABW','ARUBA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AUS','AUSTRALIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AUT','AUSTRIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AZE','AZERBAIJAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BHS','BAHAMAS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BHR','BAHRAIN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BGD','BANGLADESH',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BRB','BARBADOS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BLR','BELARUS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BEL','BELGIUM',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BLZ','BELIZE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BEN','BENIN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BMU','BERMUDA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BTN','BHUTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BOL','BOLIVIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BIH','BOSNIA AND HERZEGOWINA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BWA','BOTSWANA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BVT','BOUVET ISLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BRA','BRAZIL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IOT','BRITISH INDIAN OCEAN TERRITORY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BRN','BRUNEI DARUSSALAM',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BGR','BULGARIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BFA','BURKINA FASO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('BDI','BURUNDI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KHM','CAMBODIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CMR','CAMEROON',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CAN','CANADA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CPV','CAPE VERDE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CYM','CAYMAN ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CAF','CENTRAL AFRICAN REPUBLIC',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TCD','CHAD',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CHL','CHILE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CHN','CHINA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CXR','CHRISTMAS ISLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CCK','COCOS (KEELING) ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('COL','COLOMBIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('COM','COMOROS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('COD','CONGO, Democratic Republic of (was Zaire)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('COG','CONGO, Republic of',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('COK','COOK ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CRI','COSTA RICA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CIV','COTE D''IVOIRE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HRV','CROATIA (local name: Hrvatska)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CUB','CUBA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CYP','CYPRUS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CZE','CZECH REPUBLIC',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DNK','DENMARK',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DJI','DJIBOUTI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DMA','DOMINICA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DOM','DOMINICAN REPUBLIC',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ECU','ECUADOR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('EGY','EGYPT',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SLV','EL SALVADOR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GNQ','EQUATORIAL GUINEA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ERI','ERITREA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('EST','ESTONIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ETH','ETHIOPIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FLK','FALKLAND ISLANDS (MALVINAS)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FRO','FAROE ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FJI','FIJI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FIN','FINLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FRA','FRANCE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GUF','FRENCH GUIANA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PYF','FRENCH POLYNESIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ATF','FRENCH SOUTHERN TERRITORIES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GAB','GABON',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GMB','GAMBIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GEO','GEORGIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('DEU','GERMANY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GHA','GHANA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GIB','GIBRALTAR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GRC','GREECE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GRL','GREENLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GRD','GRENADA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GLP','GUADELOUPE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GUM','GUAM',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GTM','GUATEMALA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GIN','GUINEA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GNB','GUINEA-BISSAU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GUY','GUYANA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HTI','HAITI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HMD','HEARD AND MC DONALD ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HND','HONDURAS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HKG','HONG KONG',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('HUN','HUNGARY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ISL','ICELAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IND','INDIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IDN','INDONESIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IRN','IRAN (ISLAMIC REPUBLIC OF)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IRQ','IRAQ',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('IRL','IRELAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ISR','ISRAEL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ITA','ITALY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('JAM','JAMAICA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('JPN','JAPAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('JOR','JORDAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KAZ','KAZAKHSTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KEN','KENYA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KIR','KIRIBATI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PRK','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KOR','KOREA, REPUBLIC OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KWT','KUWAIT',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KGZ','KYRGYZSTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LAO','LAO PEOPLE''S DEMOCRATIC REPUBLIC',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LVA','LATVIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LBN','LEBANON',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LSO','LESOTHO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LBR','LIBERIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LBY','LIBYAN ARAB JAMAHIRIYA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LIE','LIECHTENSTEIN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LTU','LITHUANIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LUX','LUXEMBOURG',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MAC','MACAU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MKD','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MDG','MADAGASCAR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MWI','MALAWI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MYS','MALAYSIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MDV','MALDIVES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MLI','MALI',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MLT','MALTA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MHL','MARSHALL ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MTQ','MARTINIQUE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MRT','MAURITANIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MUS','MAURITIUS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MYT','MAYOTTE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MEX','MEXICO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('FSM','MICRONESIA, FEDERATED STATES OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MDA','MOLDOVA, REPUBLIC OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MCO','MONACO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MNG','MONGOLIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MSR','MONTSERRAT',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MAR','MOROCCO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MOZ','MOZAMBIQUE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MMR','MYANMAR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NAM','NAMIBIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NRU','NAURU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NPL','NEPAL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NLD','NETHERLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ANT','NETHERLANDS ANTILLES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NCL','NEW CALEDONIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NZL','NEW ZEALAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NIC','NICARAGUA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NER','NIGER',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NGA','NIGERIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NIU','NIUE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NFK','NORFOLK ISLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('MNP','NORTHERN MARIANA ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('NOR','NORWAY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('OMN','OMAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PAK','PAKISTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PLW','PALAU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PSE','PALESTINIAN TERRITORY, Occupied',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PAN','PANAMA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PNG','PAPUA NEW GUINEA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PRY','PARAGUAY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PER','PERU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PHL','PHILIPPINES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PCN','PITCAIRN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('POL','POLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PRT','PORTUGAL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('PRI','PUERTO RICO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('QAT','QATAR',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('REU','REUNION',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ROU','ROMANIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('RUS','RUSSIAN FEDERATION',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('RWA','RWANDA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SHN','SAINT HELENA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('KNA','SAINT KITTS AND NEVIS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LCA','SAINT LUCIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SPM','SAINT PIERRE AND MIQUELON',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VCT','SAINT VINCENT AND THE GRENADINES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('WSM','SAMOA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SMR','SAN MARINO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('STP','SAO TOME AND PRINCIPE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SAU','SAUDI ARABIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SEN','SENEGAL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SCG','SERBIA AND MONTENEGRO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SYC','SEYCHELLES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SLE','SIERRA LEONE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SGP','SINGAPORE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SVK','SLOVAKIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SVN','SLOVENIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SLB','SOLOMON ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SOM','SOMALIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ZAF','SOUTH AFRICA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SGS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ESP','SPAIN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('LKA','SRI LANKA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SDN','SUDAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SUR','SURINAME',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SJM','SVALBARD AND JAN MAYEN ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SWZ','SWAZILAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SWE','SWEDEN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CHE','SWITZERLAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('SYR','SYRIAN ARAB REPUBLIC',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TWN','TAIWAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TJK','TAJIKISTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TZA','TANZANIA, UNITED REPUBLIC OF',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('THA','THAILAND',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TLS','TIMOR-LESTE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TGO','TOGO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TKL','TOKELAU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TON','TONGA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TTO','TRINIDAD AND TOBAGO',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TUN','TUNISIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TUR','TURKEY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TKM','TURKMENISTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TCA','TURKS AND CAICOS ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('TUV','TUVALU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('UGA','UGANDA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('UKR','UKRAINE',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ARE','UNITED ARAB EMIRATES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('GBR','UNITED KINGDOM',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('USA','UNITED STATES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('UMI','UNITED STATES MINOR OUTLYING ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('URY','URUGUAY',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('UZB','UZBEKISTAN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VUT','VANUATU',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VAT','VATICAN CITY STATE (HOLY SEE)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VEN','VENEZUELA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VNM','VIET NAM',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VGB','VIRGIN ISLANDS (BRITISH)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('VIR','VIRGIN ISLANDS (U.S.)',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('WLF','WALLIS AND FUTUNA ISLANDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ESH','WESTERN SAHARA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('YEM','YEMEN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ZMB','ZAMBIA',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Country]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('ZWE','ZIMBABWE',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Confederation]
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('---','No Value',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('UEFA','Union of European Football Associations',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CONMEBOL','South American Football Confederation',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CONCACAF','Confederation of North, Central American and Caribbean Association Football',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('CAF','Confederation of African Football',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('AFC','Asian Football Confederation',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Confederation]([ShortName], [Name], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('OFC','Oceania Football Confederation',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Association]
INSERT INTO [dbo].[tbCore_Association]([ShortName],[Name],[IsActive],[ConfederationId],[CountryId],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---', 'No Value',1,1,1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Position]
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Default','-',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Goalkeeper','G',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Defender','D',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Midfielder','M',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Forward','F',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Position] ([Position], [Abbrev], [IsActive], [EntryUserId], [EntryDate], [ModUserId], [ModDate]) VALUES ('Coach','C',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Referee]
INSERT INTO [dbo].[tbCore_Referee] ([NickName],[FirstName],[MiddleName],[LastName],[IsActive],[BirthDate],[CountryId],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---','Referee','','Default',1,'1/1/2000',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Player]
INSERT INTO [dbo].[tbCore_Player] ([NickName],[FirstName],[MiddleName],[LastName],[PositionId],[IsActive],[BirthDate],[CountryId],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---','Player','','Default',5,1,'1/1/2000',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Team]
INSERT INTO [dbo].[tbCore_Team] ([ShortName],[Name],[IsActive],[AssociationId],[Alias01],[Alias02],[Alias03],[Alias04],[Alias05],[Alias06],[Alias07],[Alias08],[Alias09],[Alias10],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---','Deault',1,1,'','','','','','','','','','',1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Stat]
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('GL','GOALS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('SG','SHOOTS ON GOAL',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('SH','SHOOTS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('SV','SAVES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('FD','FOULS DRAWN',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('FC','FOULS COMMITTED',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('OF','OFFSIDES',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('PS','POSSESSION',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('YC','YELLOW CARDS',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Stat] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('RC','RED CARDS',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_Stadium]
INSERT INTO [dbo].[tbCore_Stadium] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---','No Value',1,1,@Date,1,@Date)

TRUNCATE TABLE [dbo].[tbCore_FixtureType]
INSERT INTO [dbo].[tbCore_FixtureType] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('--','No Value',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_FixtureType] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('RG','Regular',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_FixtureType] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('1L','First Leg',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_FixtureType] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('2L','Second Leg',1,1,@Date,1,@Date)
                                        
TRUNCATE TABLE [dbo].[tbCore_Phase]
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('---','No Value',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('RGL','Regular',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('GRP','Groups',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('P16','Playoff-16',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('P08','Playoff-8',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('QTF','Quater-finals',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('SMF','Semi-finals',1,1,@Date,1,@Date)
INSERT INTO [dbo].[tbCore_Phase] ([ShortName],[Name],[IsActive],[EntryUserId],[EntryDate],[ModUserId],[ModDate]) VALUES('FNL','Final',1,1,@Date,1,@Date)
